package space.accident.main.loading;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import space.accident.api.enums.MaterialList;
import space.accident.api.util.GT_LanguageManager;
import space.accident.main.items.AutoGeneratedItemsPage1;
import space.accident.main.items.ItemDebug;

import java.util.Locale;

public class PreLoading {
	public static void init(FMLPreInitializationEvent e) {
		OrePrefixInit.start();
		
		MaterialList.preLoad();
		initLang(e);
		
		initItem();
		
	}
	
	private static void initItem() {
		new ItemDebug();
		new AutoGeneratedItemsPage1();
	}
	
	private static void initLang(FMLPreInitializationEvent e) {
		Locale.setDefault(Locale.ENGLISH);
		GT_LanguageManager.initLocalization(e.getModConfigurationDirectory().getParentFile());
	}
}